version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/app/server/src
    command: nodemon -L src/server.js
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    depends_on: 
      - server
    command: npm run start
    restart: always
  